FROM node:14.16.1

ENV NODE_ENV development

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]
RUN yarn

COPY . .

EXPOSE 3000
EXPOSE 15319

CMD ["yarn", "dev", "--host", "0.0.0.0"]
